server:
  port: 8083
spring:
  application:
    name: ly-search
  data:
    elasticsearch:
       cluster-name: elasticsearch
       clusterNodes: 47.98.114.21:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: ly-search
  company.name: www.leyou.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$