server:
  port: 10010
info:
  app.name: ly-gateway
  company.name: www.leyou.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  #添加路由前缀
  prefix: /api
  routes:
    ly-item: /item/**
    ly-search: /search/**
    ly-user: /user/**
    ly-auth: /auth/**
    ly-upload:
      serviceId: ly-upload
      path: /upload/**
      stripPrefix: false
  add-host-header: true #添加头信息
  sensitive-headers:  #放行所有头
ribbon:
  ConnectTimeout: 3000 # 连接超时时间(ms)
  ReadTimeout: 5500 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：5000ms
ly:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/code
      - /api/user/check
      - /api/item